### ISSUE TITLE
howto make solrdora friendly to proxy

### ISSUE THREAD

**Issue by atomotic** [hectorcorrea/gosiah#1]
i'm trying to proxy solrdora behind nginx
using `sub_filter` i can easily rewrite hardcoded `/` for css, js and form actions.

```
location ~/browse/mycore(.*)$ {
		proxy_pass http://127.0.0.1:9001$1;
		
		proxy_set_header Accept-Encoding "";
		sub_filter_types *;
		sub_filter 'href="/' 'href="/browse/mycore/';
		sub_filter 'action="/' 'action="/browse/mycore/';
		sub_filter 'src="/' 'src="/browse/mycore/';
     		sub_filter_once off;
	}
```

however the `q=` parameter seems to be not readed with proxy, how do you suggest to modify the router?
i was thinking also to add an `externalUrl` key in `settings.json` to modify template rendering

thanks (solrdora is a great tool, i've get rid of several drupal+sarnia used to browse indexes)

**Comment by atomotic** [comment]
don't mind, actually it's enough to add a rewrite to let the proxy work

```
location /browse/mycore {
        rewrite ^/browse/mycore/(.*)$ /$1 break;
        proxy_pass http://127.0.0.1:9001;
        sub_filter_types *;
        sub_filter 'href="/' 'href="/browse/mycore/';
        sub_filter 'action="/' 'action="/browse/mycore/';
        sub_filter 'src="/' 'src="/browse/mycore/';
        sub_filter_once off;
    }
```

**Comment by hectorcorrea** [comment]
@atomotic sorry for the super late reply. I've just noticed your request from 5 months ago :( 

I am glad you were able to figure out a way around it. Let me know if there are other enhancements that you'd like -- I'll pay more attention this time.

**Comment by atomotic** [comment]
thanks anyway! i'm very happy with solrdora, i'm deploying it in every solr i manage. 
i took some notes, there are some things that could be easily fixed, i'll post you in a ticket
