### ISSUE TITLE
Solr - User Password

### ISSUE THREAD

**Issue by nmansur** [hectorcorrea/gosiah#2]
Hello, Tool seem to be interesting , i would like to use the same  but what are the parameter to pass solr user name / password could you provide the same.

**Comment by hectorcorrea** [comment]
If you have Solr's [Basic Authentication](https://lucene.apache.org/solr/guide/7_0/basic-authentication-plugin.html) enabled you can pass the credentials on the URL to connect to Solr directly on solrCoreUrl value in [settings.json](https://github.com/hectorcorrea/solrdora/blob/master/settings.json#L3), for example change the value to 

```
"solrCoreUrl": "http://your-user-name:your-password@localhost:8983/solr/bibdata"
```

**Comment by nmansur** [comment]
Thank you,

One more question, search doesn't seem to work with q:?  Even though searchFL is configured.

I was expecting it to work out of box, let me know if you can suggest sample
thanks,
Naveen
________________________________
