### ISSUE TITLE
A minor problem about the first-last value in the searchResult

### ISSUE THREAD

**Issue by vulcangz** [hectorcorrea/gosiah#3]
First of all, thank you for providing such a useful tool for solr - solrdora!

It feels like there is something wrong with the following two lines of code.
https://github.com/hectorcorrea/solrdora/blob/4101bed269e7dd43ff7860ade6dc58e8fffd3074/models/searchResults.go#L37-L38

Suppose
```
results.Start = 0
results.Row = 10
```
After code execution.
```
results.First = 1
results.Last= 11 (not 10)
```
In that case: from 1 to 11, the Row value is 11.

This might work.
```
 results.First = results.Start + 1 
 results.Last = results.Start + results.Rows 
```

**Comment by hectorcorrea** [comment]
Thanks for the heads up. I'll take a look at it this weekend.
