### ISSUE TITLE
Change fields labels

### ISSUE THREAD

**Issue by ronniebrito** [hectorcorrea/gosiah#4]
Hi Hector, 

how could we change the field label presented in the results, like

vivo_hasSubjectArea_ss: Ciências Agrárias

would be 

Area do Conhecimento:  Ciências Agrárias

thank you

**Comment by hectorcorrea** [comment]
@ronniebrito you could overwrite the files `./views/one.html` and `./views/results.html`. The default files that came with the repo just loop through the fields and display field name + value, but you could overwrite these views to include logic for each different field. I have a couple of examples here:

* one.html - https://gist.github.com/hectorcorrea/88bc58afce030c84bad039b79f14f78b
* results.html - https://gist.github.com/hectorcorrea/6cd3dc01f5052d7f42d87f2a1566a584

These two examples are hard-coded for very specific fields (id, title_txt_en, authors_all_txts_en, and subjects_txts_en) but they should give you an idea of how to go about it.

At some point I should allow users to specify the display label for each field in the `settings.json` (like I do for the Facet label) but I have not added that feature.

**Comment by ronniebrito** [comment]
thank you!!!
