### ISSUE TITLE
Selected filelds shown in alphabetical order

### ISSUE THREAD

**Issue by rccarrasco** [hectorcorrea/gosiah#5]
Thanks for the nice implementation.
The list of fields declared in the configuration file are not shown in the specified order and they seem to be alphabetically ordered. This is not convenient in many cases, for example, in a document repository with "searchFL" = ["document_id", "abstract"] , the abstract appears before the id, which  is not standard.
As my knowledge of go is none, I cannot help to identify the reason.

**Comment by hectorcorrea** [comment]
@rccarrasco yeah, the default views one.html and results.html just loop through the fields and there is no way to guarantee the order. 

I have a couple of examples here on how to customize those views to be explicit about the fields and their order:
* `one.html` - https://gist.github.com/hectorcorrea/88bc58afce030c84bad039b79f14f78b
* `results.html` - https://gist.github.com/hectorcorrea/6cd3dc01f5052d7f42d87f2a1566a584

I hope these help you get your display the way you want to.
